version: '3.3'

volumes:
  foodgram_data:
  static:
  media:

services:

  foodgram_db:
    image: postgres:13.0
    volumes:
      - foodgram_data:/var/lib/postgresql/data
    env_file: ../.env
    ports:
      - "5435:5432"
    restart: always
