"""fifth

Revision ID: 27da59e6cbc4
Revises: 1e4364766fce
Create Date: 2023-11-24 11:10:55.041431

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27da59e6cbc4'
down_revision: Union[str, None] = '1e4364766fce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favorites', sa.Column('recipe_id', sa.Integer(), nullable=False))
    op.drop_constraint('unique_recipe_favorites_user_favorites', 'favorites', type_='unique')
    op.create_unique_constraint('unique_recipe_favorites_user_favorites', 'favorites', ['user_id', 'recipe_id'])
    op.drop_constraint('favorites_recipes_id_fkey', 'favorites', type_='foreignkey')
    op.create_foreign_key(None, 'favorites', 'recipes', ['recipe_id'], ['id'], ondelete='CASCADE')
    op.drop_column('favorites', 'recipes_id')
    op.add_column('purchase_carts', sa.Column('recipe_id', sa.Integer(), nullable=False))
    op.drop_constraint('unique_recipe_carts_user_carts', 'purchase_carts', type_='unique')
    op.create_unique_constraint('unique_recipe_carts_user_carts', 'purchase_carts', ['user_id', 'recipe_id'])
    op.drop_constraint('purchase_carts_recipes_id_fkey', 'purchase_carts', type_='foreignkey')
    op.create_foreign_key(None, 'purchase_carts', 'recipes', ['recipe_id'], ['id'], ondelete='CASCADE')
    op.drop_column('purchase_carts', 'recipes_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase_carts', sa.Column('recipes_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'purchase_carts', type_='foreignkey')
    op.create_foreign_key('purchase_carts_recipes_id_fkey', 'purchase_carts', 'recipes', ['recipes_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('unique_recipe_carts_user_carts', 'purchase_carts', type_='unique')
    op.create_unique_constraint('unique_recipe_carts_user_carts', 'purchase_carts', ['user_id', 'recipes_id'])
    op.drop_column('purchase_carts', 'recipe_id')
    op.add_column('favorites', sa.Column('recipes_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'favorites', type_='foreignkey')
    op.create_foreign_key('favorites_recipes_id_fkey', 'favorites', 'recipes', ['recipes_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('unique_recipe_favorites_user_favorites', 'favorites', type_='unique')
    op.create_unique_constraint('unique_recipe_favorites_user_favorites', 'favorites', ['user_id', 'recipes_id'])
    op.drop_column('favorites', 'recipe_id')
    # ### end Alembic commands ###
