"""fixes

Revision ID: 3d35798e047f
Revises: e11c4d9961f6
Create Date: 2024-02-13 15:32:23.682216

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = '3d35798e047f'
down_revision: Union[str, None] = 'e11c4d9961f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'ingredient', ['name'])
    op.create_unique_constraint(None, 'tag', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tag', type_='unique')
    op.drop_constraint(None, 'ingredient', type_='unique')
    # ### end Alembic commands ###
