"""third

Revision ID: 59998ccbabda
Revises: 18a86aa1ae01
Create Date: 2023-11-24 10:10:29.268613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59998ccbabda'
down_revision: Union[str, None] = '18a86aa1ae01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('follows', sa.Column('follower_id', sa.Integer(), nullable=False))
    op.drop_constraint('unique_following_user_following', 'follows', type_='unique')
    op.create_unique_constraint('unique_follower_to_following', 'follows', ['follower_id', 'following_id'])
    op.drop_constraint('follows_user_id_fkey', 'follows', type_='foreignkey')
    op.create_foreign_key(None, 'follows', 'users', ['follower_id'], ['id'], ondelete='CASCADE')
    op.drop_column('follows', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('follows', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'follows', type_='foreignkey')
    op.create_foreign_key('follows_user_id_fkey', 'follows', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('unique_follower_to_following', 'follows', type_='unique')
    op.create_unique_constraint('unique_following_user_following', 'follows', ['user_id', 'following_id'])
    op.drop_column('follows', 'follower_id')
    # ### end Alembic commands ###
