"""del fastapi_users

Revision ID: 6c80dad5ce6e
Revises: ef6db5e7d547
Create Date: 2023-11-28 15:30:43.388174

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '6c80dad5ce6e'
down_revision: Union[str, None] = 'ef6db5e7d547'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
